// data/tableData.js
export const tableData = {
    // -------------------- SISWA --------------------
    siswa: [
        {
            "ID": 123001,
            "Nama": "John Doe",
            "NIS": "12345",
            "NIK": "67890",
            "No.KK": "54321",
            "Tempat Lahir": "Jakarta",
            "Tanggal Lahir": "2005-01-01",
            "Alamat": "123 Main St",
            "Tahun Masuk": "2021",
        },
        {
            "ID": 123002,
            "Nama": "Jane Doe",
            "NIS": "54321",
            "NIK": "98765",
            "No.KK": "13579",
            "Tempat Lahir": "Bandung",
            "Tanggal Lahir": "2004-02-02",
            "Alamat": "456 Secondary St",
            "Tahun Masuk": "2020",
        },
        {
            "ID": 123003,
            "Nama": "Michael Johnson",
            "NIS": "11111",
            "NIK": "22222",
            "No.KK": "33333",
            "Tempat Lahir": "Surabaya",
            "Tanggal Lahir": "2006-03-03",
            "Alamat": "789 Fourth St",
            "Tahun Masuk": "2021",
        },
        {
            "ID": 123004,
            "Nama": "Sophia Williams",
            "NIS": "44444",
            "NIK": "55555",
            "No.KK": "66666",
            "Tempat Lahir": "Yogyakarta",
            "Tanggal Lahir": "2003-04-04",
            "Alamat": "1010 Fifth St",
            "Tahun Masuk": "2019",
        },
        {
            "ID": 123005,
            "Nama": "Ethan Brown",
            "NIS": "77777",
            "NIK": "88888",
            "No.KK": "99999",
            "Tempat Lahir": "Medan",
            "Tanggal Lahir": "2002-05-05",
            "Alamat": "1212 Sixth St",
            "Tahun Masuk": "2020",
        },
        {
            "ID": 123006,
            "Nama": "Olivia Garcia",
            "NIS": "10101",
            "NIK": "20202",
            "No.KK": "30303",
            "Tempat Lahir": "Denpasar",
            "Tanggal Lahir": "2001-06-06",
            "Alamat": "1414 Seventh St",
            "Tahun Masuk": "2018",
        },
        {
            "ID": 123007,
            "Nama": "Liam Rodriguez",
            "NIS": "40404",
            "NIK": "50505",
            "No.KK": "60606",
            "Tempat Lahir": "Semarang",
            "Tanggal Lahir": "2000-07-07",
            "Alamat": "1616 Eighth St",
            "Tahun Masuk": "2017",
        },
        {
            "ID": 123008,
            "Nama": "Ava Martinez",
            "NIS": "70707",
            "NIK": "80808",
            "No.KK": "90909",
            "Tempat Lahir": "Bali",
            "Tanggal Lahir": "1999-08-08",
            "Alamat": "1818 Ninth St",
            "Tahun Masuk": "2016",
        },
        {
            "ID": 123009,
            "Nama": "William Hernandez",
            "NIS": "11112",
            "NIK": "13131",
            "No.KK": "15151",
            "Tempat Lahir": "Palembang",
            "Tanggal Lahir": "1998-09-09",
            "Alamat": "2020 Tenth St",
            "Tahun Masuk": "2015",
        },
        {
            "ID": 123010,
            "Nama": "Robert Smith",
            "NIS": "56789",
            "NIK": "23456",
            "No.KK": "98765",
            "Tempat Lahir": "Surabaya",
            "Tanggal Lahir": "2003-03-03",
            "Alamat": "789 Third St",
            "Tahun Masuk": "2019",
        },
    ],

    // -------------------- GURU ---------------------
    guru: [
        {
            "ID": 223001,
            "Nama": "Jane Doe",
            "NIK": "54321",
            "Tempat Lahir": "Bandung",
            "TGL Lahir": "1980-05-15",
            "Alamat": "456 Secondary St",
            "Lulusan": "S1",
            "Jurusan": "Teknik Informatika",
            "Perguruan Tinggi": "Universitas XYZ",
            "Sertifikat": "Certification XYZ",
            "File": "file_xyz.pdf",
            "Ijazah": "Ijazah XYZ",
            "KTP": "ktp_xyz.jpg",
        },
        {
            "ID": 223002,
            "Nama": "Michael Smith",
            "NIK": "98765",
            "Tempat Lahir": "Surabaya",
            "TGL Lahir": "1978-10-10",
            "Alamat": "789 Main St",
            "Lulusan": "S2",
            "Jurusan": "Manajemen",
            "Perguruan Tinggi": "Universitas ABC",
            "Sertifikat": "Certification ABC",
            "File": "file_abc.pdf",
            "Ijazah": "Ijazah ABC",
            "KTP": "ktp_abc.jpg",
        },
        {
            "ID": 223003,
            "Nama": "Emily Brown",
            "NIK": "54322",
            "Tempat Lahir": "Medan",
            "TGL Lahir": "1982-11-20",
            "Alamat": "246 Tertiary St",
            "Lulusan": "S3",
            "Jurusan": "Seni Rupa",
            "Perguruan Tinggi": "Universitas GHI",
            "Sertifikat": "Certification GHI",
            "File": "file_ghi.pdf",
            "Ijazah": "Ijazah GHI",
            "KTP": "ktp_ghi.jpg",
        },
        {
            "ID": 223004,
            "Nama": "Daniel Wilson",
            "NIK": "98766",
            "Tempat Lahir": "Bali",
            "TGL Lahir": "1983-09-30",
            "Alamat": "135 Fourth St",
            "Lulusan": "S1",
            "Jurusan": "Hukum",
            "Perguruan Tinggi": "Universitas JKL",
            "Sertifikat": "Certification JKL",
            "File": "file_jkl.pdf",
            "Ijazah": "Ijazah JKL",
            "KTP": "ktp_jkl.jpg",
        },
        {
            "ID": 223005,
            "Nama": "Sophia Garcia",
            "NIK": "13579",
            "Tempat Lahir": "Yogyakarta",
            "TGL Lahir": "1984-08-05",
            "Alamat": "678 Fifth St",
            "Lulusan": "S2",
            "Jurusan": "Pendidikan",
            "Perguruan Tinggi": "Universitas MNO",
            "Sertifikat": "Certification MNO",
            "File": "file_mno.pdf",
            "Ijazah": "Ijazah MNO",
            "KTP": "ktp_mno.jpg",
        },
        {
            "ID": 223006,
            "Nama": "Oliver Martinez",
            "NIK": "54320",
            "Tempat Lahir": "Surabaya",
            "TGL Lahir": "1985-07-15",
            "Alamat": "910 Sixth St",
            "Lulusan": "S3",
            "Jurusan": "Psikologi",
            "Perguruan Tinggi": "Universitas PQR",
            "Sertifikat": "Certification PQR",
            "File": "file_pqr.pdf",
            "Ijazah": "Ijazah PQR",
            "KTP": "ktp_pqr.jpg",
        },
        {
            "ID": 223007,
            "Nama": "Emma Johnson",
            "NIK": "24681",
            "Tempat Lahir": "Semarang",
            "TGL Lahir": "1986-06-10",
            "Alamat": "111 Seventh St",
            "Lulusan": "S1",
            "Jurusan": "Kimia",
            "Perguruan Tinggi": "Universitas STU",
            "Sertifikat": "Certification STU",
            "File": "file_stu.pdf",
            "Ijazah": "Ijazah STU",
            "KTP": "ktp_stu.jpg",
        },
        {
            "ID": 223008,
            "Nama": "William Lee",
            "NIK": "98767",
            "Tempat Lahir": "Bekasi",
            "TGL Lahir": "1987-05-25",
            "Alamat": "121 Eighth St",
            "Lulusan": "S2",
            "Jurusan": "Ilmu Komputer",
            "Perguruan Tinggi": "Universitas VWX",
            "Sertifikat": "Certification VWX",
            "File": "file_vwx.pdf",
            "Ijazah": "Ijazah VWX",
            "KTP": "ktp_vwx.jpg",
        },
        {
            "ID": 223009,
            "Nama": "Olivia Clark",
            "NIK": "54323",
            "Tempat Lahir": "Bandung",
            "TGL Lahir": "1988-04-20",
            "Alamat": "131 Ninth St",
            "Lulusan": "S1",
            "Jurusan": "Bisnis",
            "Perguruan Tinggi": "Universitas YZ",
            "Sertifikat": "Certification YZ",
            "File": "file_yz.pdf",
            "Ijazah": "Ijazah YZ",
            "KTP": "ktp_yz.jpg",
        },
        {
            "ID": 223010,
            "Nama": "Emily Johnson",
            "NIK": "24680",
            "Tempat Lahir": "Jakarta",
            "TGL Lahir": "1981-12-25",
            "Alamat": "123 Secondary St",
            "Lulusan": "S3",
            "Jurusan": "Ekonomi",
            "Perguruan Tinggi": "Universitas DEF",
            "Sertifikat": "Certification DEF",
            "File": "file_def.pdf",
            "Ijazah": "Ijazah DEF",
            "KTP": "ktp_def.jpg",
        },
        {
            "ID": 223011,
            "Nama": "Emily Johnson Liebert",
            "NIK": "24680",
            "Tempat Lahir": "Jakarta",
            "TGL Lahir": "1981-12-25",
            "Alamat": "123 Secondary St",
            "Lulusan": "S3",
            "Jurusan": "Ekonomi",
            "Perguruan Tinggi": "Universitas DEF",
            "Sertifikat": "Certification DEF",
            "File": "file_def.pdf",
            "Ijazah": "Ijazah DEF",
            "KTP": "ktp_def.jpg",
        },
    ],

    // ------------------ KELUARGA -------------------
    keluarga: [
        {
            "ID": 323001,
            "Nama Siswa": "John Doe",
            "Keterangan Keluarga": "Ayah",
            "Nama": "John's Father",
            "Pekerjaan": "Engineer",
            "Alamat": "789 Family St",
            "Pendapatan": "$60,000",
            "Lulusan": "SMA",
        },
        {
            "ID": 323002,
            "Nama Siswa": "Jane Doe",
            "Keterangan Keluarga": "Ibu",
            "Nama": "Jane's Mother",
            "Pekerjaan": "Doctor",
            "Alamat": "456 Family St",
            "Pendapatan": "$80,000",
            "Lulusan": "S2",
        },
        {
            "ID": 323003,
            "Nama Siswa": "Michael Smith",
            "Keterangan Keluarga": "Ayah",
            "Nama": "Michael's Father",
            "Pekerjaan": "Lawyer",
            "Alamat": "333 Family St",
            "Pendapatan": "$90,000",
            "Lulusan": "S3",
        },
        {
            "ID": 323004,
            "Nama Siswa": "Sophia Garcia",
            "Keterangan Keluarga": "Ibu",
            "Nama": "Sophia's Mother",
            "Pekerjaan": "Professor",
            "Alamat": "222 Family St",
            "Pendapatan": "$100,000",
            "Lulusan": "S1",
        },
        {
            "ID": 323005,
            "Nama Siswa": "Ethan Brown",
            "Keterangan Keluarga": "Ayah",
            "Nama": "Ethan's Father",
            "Pekerjaan": "Artist",
            "Alamat": "111 Family St",
            "Pendapatan": "$70,000",
            "Lulusan": "S2",
        },
        {
            "ID": 323006,
            "Nama Siswa": "Olivia Garcia",
            "Keterangan Keluarga": "Ibu",
            "Nama": "Olivia's Mother",
            "Pekerjaan": "Engineer",
            "Alamat": "444 Parent St",
            "Pendapatan": "$90,000",
            "Lulusan": "S3",
        },
        {
            "ID": 323007,
            "Nama Siswa": "Liam Rodriguez",
            "Keterangan Keluarga": "Ayah",
            "Nama": "Liam's Father",
            "Pekerjaan": "Chef",
            "Alamat": "555 Family St",
            "Pendapatan": "$80,000",
            "Lulusan": "S1",
        },
        {
            "ID": 323008,
            "Nama Siswa": "Ava Martinez",
            "Keterangan Keluarga": "Ibu",
            "Nama": "Ava's Mother",
            "Pekerjaan": "Consultant",
            "Alamat": "666 Family St",
            "Pendapatan": "$95,000",
            "Lulusan": "S2",
        },
        {
            "ID": 323009,
            "Nama Siswa": "William Hernandez",
            "Keterangan Keluarga": "Ayah",
            "Nama": "William's Father",
            "Pekerjaan": "Pilot",
            "Alamat": "777 Family St",
            "Pendapatan": "$110,000",
            "Lulusan": "S3",
        },
        {
            "ID": 323010,
            "Nama Siswa": "Robert Smith",
            "Keterangan Keluarga": "Ayah",
            "Nama": "Robert's Father",
            "Pekerjaan": "Architect",
            "Alamat": "789 Parent St",
            "Pendapatan": "$70,000",
            "Lulusan": "S1",
        },
    ],

    // -------------------- ROLE ---------------------
    role: [
        {
            "ID": 423001,
            "Nama": "John Doe",
            "Kelas": "12A",
            "Role": "Admin",
        },
        {
            "ID": 423002,
            "Nama": "Jane Doe",
            "Kelas": "11B",
            "Role": "User",
        },
        {
            "ID": 423003,
            "Nama": "Michael Smith",
            "Kelas": "10C",
            "Role": "Admin",
        },
        {
            "ID": 423004,
            "Nama": "Sophia Garcia",
            "Kelas": "9A",
            "Role": "User",
        },
        {
            "ID": 423005,
            "Nama": "Ethan Brown",
            "Kelas": "12B",
            "Role": "Admin",
        },
        {
            "ID": 423006,
            "Nama": "Olivia Garcia",
            "Kelas": "11A",
            "Role": "User",
        },
        {
            "ID": 423007,
            "Nama": "Liam Rodriguez",
            "Kelas": "10B",
            "Role": "Admin",
        },
        {
            "ID": 423008,
            "Nama": "Ava Martinez",
            "Kelas": "9C",
            "Role": "User",
        },
        {
            "ID": 423009,
            "Nama": "William Hernandez",
            "Kelas": "12C",
            "Role": "Admin",
        },
        {
            "ID": 423010,
            "Nama": "Robert Smith",
            "Kelas": "11B",
            "Role": "User",
        },
    ],
};
